In [38]:
from sklearn.datasets import load_diabetes

In [39]:
import numpy as np

In [40]:
X,y=load_diabetes(return_X_y=True)

In [41]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [43]:
model = LinearRegression()

In [44]:
model.fit(X_train,y_train)

LinearRegression()

In [45]:
model.coef_

array([  19.92730105, -262.5526422 ,  509.19584695,  336.09319329,
       -849.30479304,  480.22664735,  120.69064852,  236.72228404,
        716.61278802,   70.41001991])

In [46]:
model.intercept_

151.7226464572191

In [47]:
model.predict(X_test)

array([143.06549158, 177.7061702 , 134.79901866, 288.67009951,
       123.58658064,  96.64279345, 252.70727574, 183.51437294,
        93.96679126, 109.83567271,  98.04584067, 168.6157848 ,
        58.09603726, 206.59004617, 102.4046759 , 130.25483366,
       218.05518616, 245.91819051, 193.24561396, 214.36953807,
       208.82839114,  90.55628576,  74.15157442, 187.12342576,
       156.3642741 , 157.46594185, 184.17437321, 177.18270901,
        52.24311033, 110.66618343, 174.05770617,  90.8969391 ,
       133.07838489, 183.22702102, 173.93636697, 189.8528273 ,
       125.8627716 , 121.53079768, 148.94645924,  60.82914409,
        76.36004131, 106.39774469, 162.2028406 , 153.15220926,
       174.23219731])

In [48]:
class olnLR:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        betas=np.dot(np.linalg.inv(np.dot(x_train.T,x_train)) , np.dot(x_train.T,y_train))
        self.intercept_=betas[0]
        self.coef_=betas[1:]
    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_) + self.intercept_
        return y_pred

In [49]:
model2=olnLR()

In [50]:
model2.fit(X_train,y_train)

In [51]:
model2.intercept_

151.72264645721907

In [52]:
model2.coef_

array([  19.92730105, -262.5526422 ,  509.19584695,  336.09319329,
       -849.30479304,  480.22664735,  120.69064852,  236.72228404,
        716.61278802,   70.41001991])

In [53]:
model2.predict(X_test)

array([143.06549158, 177.7061702 , 134.79901866, 288.67009951,
       123.58658064,  96.64279345, 252.70727574, 183.51437294,
        93.96679126, 109.83567271,  98.04584067, 168.6157848 ,
        58.09603726, 206.59004617, 102.4046759 , 130.25483366,
       218.05518616, 245.91819051, 193.24561396, 214.36953807,
       208.82839114,  90.55628576,  74.15157442, 187.12342576,
       156.3642741 , 157.46594185, 184.17437321, 177.18270901,
        52.24311033, 110.66618343, 174.05770617,  90.8969391 ,
       133.07838489, 183.22702102, 173.93636697, 189.8528273 ,
       125.8627716 , 121.53079768, 148.94645924,  60.82914409,
        76.36004131, 106.39774469, 162.2028406 , 153.15220926,
       174.23219731])