In [78]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression

In [79]:
X,y=make_regression(n_features=1)

# Mylinear Regression simple

In [80]:
class MyLR:
    def __init__(self):
        self.m=None
        self.b=None
    def fit(self,x_train,y_train):
        num=0
        den=0
        for i in range(x_train.shape[0]):
          num +=(y_train[i] -y_train.mean()) * (x_train[i] - x_train.mean())
          den += (x_train[i] - x_train.mean())**2
        self.m= num/den
        self.b=(y_train.mean() - (self.m * x_train.mean()))
    def pridect(self,x_test):
        return self.m * x_test + self.b


In [81]:
from sklearn.model_selection import train_test_split

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [83]:
mymodel=MyLR()

In [84]:
mymodel.fit(X_train,y_train)

In [85]:
mymodel.pridect(X_test)

array([[  24.62273331],
       [ -26.8298836 ],
       [  60.705663  ],
       [ -59.82409916],
       [  30.51017879],
       [  -3.56078468],
       [ -48.98182597],
       [   7.07496872],
       [-160.76434371],
       [ -11.5869574 ]])

In [86]:
mymodel.m

array([58.25748849])

In [87]:
mymodel.b

array([4.4408921e-16])

# skLearn Linear Regression 

In [88]:
from sklearn.linear_model import LinearRegression

In [89]:
model=LinearRegression()

In [90]:
model.fit(X_train,y_train)

LinearRegression()

In [91]:
model.coef_

array([58.25748849])

In [92]:
model.intercept_

4.440892098500626e-16